In [321]:
import pandas as pd;
import numpy as np;

In [322]:
spam_dictionary=['Free','Click here','visit','open attachment',
                 'call this number','money','Out','extra','offer','available','Pension','Opportunity','Chance','Investment','Pension'];
spam_dictionary=[w.lower() for w in spam_dictionary]

In [323]:
doc_1=('I wanted to let you know about money that is available for college in your State .The amount is up to $5,730* if you qualify.'
'It takes like 2 minutes to check if you qualify.Click Here to get matched.')
doc_2=('Free -Coupons for next movie. T he above links will take you straight to our partner\'s site. For more information or to see other'
'offers available, you can also visit the Groupon on the Working Advantage website.')
doc_3=('Our records indicate your Pension is under performing to see higher growth and up to 25% cash release reply PENSION for a free review.'
'To opt out reply STOP')
doc_4=('Enter to win $25,000 and get a Free Hotel Night! Just click here for a $1 trial membership in NetMarket, the Internet\'spremier '
'discount shopping site: Fast Company EZVenture gives you FREE business articles,PLUS, you could win YOUR CHOICE of a BMW Z3 convertible, '
'$100,000, shares of Microsoft stock, or a home office computer. Go there and get your chances to win now. A crazy-funny-cool trivia book '
'with a $10,000 prize? PLUS chocolate, nail polish, cats, barnyard animals, and more?')
doc_5=('Dear recipient,Avangar Technologies announces the beginning of a new unprecendented global employment campaign.Due to company\'s '
'exploding growth Avangar is expanding business to the European region.During last employment campaign over 1500 people worldwide took part' 
'in Avangar\'s business and more than half of them are currently employed by the company. And now we are offering you one more opportunity to '
'earn extra money working with Avangar Technologies. We are looking for honest, responsible, hard-working people that can dedicate 2-4 hours '
'of their time per day and earn extra £300-500 weekly. All offered positions are currently part-time and give you a chance to work mainly from home.')

In [324]:
doc_1

'I wanted to let you know about money that is available for college in your State .The amount is up to $5,730* if you qualify.It takes like 2 minutes to check if you qualify.Click Here to get matched.'

In [325]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize 

In [326]:
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/chidananda.pati/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     /Users/chidananda.pati/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [327]:
stop_words=set(stopwords.words('english'))

In [328]:
def filtered_doc(doc):
    doc_word_tokens = word_tokenize(doc) 
    doc_filtered = [w.lower() for w in doc_word_tokens if not w in stop_words] 
    return doc_filtered;

doc_1_tokens=filtered_doc(doc_1)
doc_2_tokens=filtered_doc(doc_2)
doc_3_tokens=filtered_doc(doc_3)
doc_4_tokens=filtered_doc(doc_4)
doc_5_tokens=filtered_doc(doc_5)

In [329]:
from math import log
def tf(term_freq):
    if (term_freq == 0):
        return 0;
    else:
        return round(1+log(1+log(term_freq,10),10),4)

In [330]:
def idf(total_num_docs,total_num_docs_with_term):
    return round(log((1+total_num_docs)/total_num_docs_with_term,10),4)

In [331]:
def tf_idf(term_freq,total_num_docs,total_num_docs_with_term):
    return round(tf(term_freq)*idf(total_num_docs,total_num_docs_with_term),4);

In [332]:
idf(5,3)

0.301

In [333]:
from collections import Counter
def term_freq(terms,doc):
    counts=Counter(doc);
    return [counts[term] for term in terms];  

def docs_with_term(terms,docs):
    docs_with_term_arr=np.zeros(len(terms))
    for idx in range(len(terms)):
        count=0;
        term=terms[idx]
        for doc in docs:
            if term in doc:
                count=count+1;
                docs_with_term_arr[idx]=count;
    return docs_with_term_arr;            

In [334]:
docs=[]
docs.append(doc_1_tokens)
docs.append(doc_2_tokens)
docs.append(doc_3_tokens)
docs.append(doc_4_tokens)
docs.append(doc_5_tokens)

In [335]:
#spam_dictionary=['Free','Click here','visit','open attachment',
#                 'call this number','money','Out','extra','offer','available','Pension','Opportunity','Chance','Investment','Pension'];
docs_with_term_arr=docs_with_term(spam_dictionary,docs)
spam_dictionary_non_zero=['Free','visit','money','extra','available','Pension','Opportunity','Chance','Pension'];
spam_dictionary_non_zero=[w.lower() for w in spam_dictionary_non_zero]
docs_with_term_arr=docs_with_term(spam_dictionary_non_zero,docs)
docs_with_term_arr

array([3., 1., 2., 1., 2., 1., 1., 1., 1.])

In [336]:
docs_with_term_arr[[np.nonzero(docs_with_term_arr)]]

array([[3., 1., 2., 1., 2., 1., 1., 1., 1.]])

In [337]:
tf_idf_matrix=np.zeros((len(docs),np.size(spam_dictionary_non_zero)))

In [338]:
for rowIdx in range(tf_idf_matrix.shape[0]):
    term_freq_doc=term_freq(spam_dictionary_non_zero,docs[rowIdx])
    for colIdx in range(tf_idf_matrix.shape[1]):
        tf_idf_matrix[rowIdx,colIdx] =tf_idf(term_freq_doc[colIdx],5,docs_with_term_arr[rowIdx])

In [339]:
print(spam_dictionary_non_zero)
print(tf_idf_matrix)

['free', 'visit', 'money', 'extra', 'available', 'pension', 'opportunity', 'chance', 'pension']
[[0.     0.     0.301  0.     0.301  0.     0.     0.     0.    ]
 [0.7782 0.7782 0.     0.     0.7782 0.     0.     0.     0.    ]
 [0.4771 0.     0.     0.     0.     0.5316 0.     0.     0.5316]
 [0.8671 0.     0.     0.     0.     0.     0.     0.     0.    ]
 [0.     0.     0.4771 0.5316 0.     0.     0.4771 0.4771 0.    ]]
